// Generated by tilelang.dataflow.abi_schema; do not edit manually.
#pragma once

#include <cstddef>
#include <cstdint>

namespace tl {

static constexpr uint32_t kDataflowABIVersion = 7u;
static constexpr uint32_t kDataflowInvalidIndex = 0xffffffffu;
static constexpr uint32_t kDataflowSlotFlagScratchBacked = 1u;
static constexpr uint32_t kDataflowSlotFlagHBMDirectGlobal = 2u;
static constexpr uint32_t kDataflowSlotFlagClusterGatedPush = 4u;
static constexpr uint32_t kDataflowSlotFlagCommunicate = 8u;
static constexpr uint32_t kDataflowHandoffFlagProducer = 1u;
static constexpr uint32_t kDataflowHandoffFlagConsumer = 2u;
static constexpr uint32_t kDataflowHandoffFlagTail = 4u;
static constexpr uint32_t kDataflowHandoffFlagDisabled = 8u;

enum class DataflowOpcode : uint32_t {
  kExit = 0,
  kIter = 1,
  kReduce = 2,
  kFinalize = 3,
  kClusterSync = 4,
};

enum class DataflowCommKind : uint32_t {
  kNone = 0,
  kClusterSend = 1,
  kClusterRecv = 2,
  kHBMSend = 3,
  kHBMRecv = 4,
  kClusterRelease = 5,
  kHBMRecvIssue = 6,
  kHBMRecvWait = 7,
};

enum class DataflowTensorDTypeCode : uint32_t {
  kUnknown = 0,
  kInt = 1,
  kUInt = 2,
  kFloat = 3,
  kBFloat = 4,
  kBool = 5,
};

struct alignas(16) DataflowInstruction {
  uint32_t opcode;
  uint32_t handler_id;
  uint32_t task_id;
  uint32_t arg_offset;
  uint32_t comm_offset;
  uint32_t comm_count;
  uint32_t slot_id;
  uint32_t flags;
};

static_assert(sizeof(DataflowInstruction) == 32,
              "DataflowInstruction ABI size mismatch");
static_assert(alignof(DataflowInstruction) == 16,
              "DataflowInstruction ABI alignment mismatch");
static_assert(offsetof(DataflowInstruction, opcode) == 0,
              "DataflowInstruction::opcode ABI offset mismatch");
static_assert(offsetof(DataflowInstruction, handler_id) == 4,
              "DataflowInstruction::handler_id ABI offset mismatch");
static_assert(offsetof(DataflowInstruction, task_id) == 8,
              "DataflowInstruction::task_id ABI offset mismatch");
static_assert(offsetof(DataflowInstruction, arg_offset) == 12,
              "DataflowInstruction::arg_offset ABI offset mismatch");
static_assert(offsetof(DataflowInstruction, comm_offset) == 16,
              "DataflowInstruction::comm_offset ABI offset mismatch");
static_assert(offsetof(DataflowInstruction, comm_count) == 20,
              "DataflowInstruction::comm_count ABI offset mismatch");
static_assert(offsetof(DataflowInstruction, slot_id) == 24,
              "DataflowInstruction::slot_id ABI offset mismatch");
static_assert(offsetof(DataflowInstruction, flags) == 28,
              "DataflowInstruction::flags ABI offset mismatch");

struct alignas(16) DataflowHandlerArgs {
  uint32_t task_id;
  uint32_t task_coord_offset;
  uint32_t task_coord_count;
  uint32_t range_begin;
  uint32_t range_end;
  uint32_t input_slot_offset;
  uint32_t input_slot_count;
  uint32_t output_slot;
  uint32_t handoff_peer_arg_offset;
  uint32_t handoff_plan_index;
  uint32_t handoff_binding_index;
  uint32_t handoff_stage_count;
  uint32_t handoff_arena_slot;
  uint32_t handoff_flags;
  uint32_t reserved0;
  uint32_t reserved1;
};

static_assert(sizeof(DataflowHandlerArgs) == 64,
              "DataflowHandlerArgs ABI size mismatch");
static_assert(alignof(DataflowHandlerArgs) == 16,
              "DataflowHandlerArgs ABI alignment mismatch");
static_assert(offsetof(DataflowHandlerArgs, task_id) == 0,
              "DataflowHandlerArgs::task_id ABI offset mismatch");
static_assert(offsetof(DataflowHandlerArgs, task_coord_offset) == 4,
              "DataflowHandlerArgs::task_coord_offset ABI offset mismatch");
static_assert(offsetof(DataflowHandlerArgs, task_coord_count) == 8,
              "DataflowHandlerArgs::task_coord_count ABI offset mismatch");
static_assert(offsetof(DataflowHandlerArgs, range_begin) == 12,
              "DataflowHandlerArgs::range_begin ABI offset mismatch");
static_assert(offsetof(DataflowHandlerArgs, range_end) == 16,
              "DataflowHandlerArgs::range_end ABI offset mismatch");
static_assert(offsetof(DataflowHandlerArgs, input_slot_offset) == 20,
              "DataflowHandlerArgs::input_slot_offset ABI offset mismatch");
static_assert(offsetof(DataflowHandlerArgs, input_slot_count) == 24,
              "DataflowHandlerArgs::input_slot_count ABI offset mismatch");
static_assert(offsetof(DataflowHandlerArgs, output_slot) == 28,
              "DataflowHandlerArgs::output_slot ABI offset mismatch");
static_assert(
    offsetof(DataflowHandlerArgs, handoff_peer_arg_offset) == 32,
    "DataflowHandlerArgs::handoff_peer_arg_offset ABI offset mismatch");
static_assert(offsetof(DataflowHandlerArgs, handoff_plan_index) == 36,
              "DataflowHandlerArgs::handoff_plan_index ABI offset mismatch");
static_assert(offsetof(DataflowHandlerArgs, handoff_binding_index) == 40,
              "DataflowHandlerArgs::handoff_binding_index ABI offset mismatch");
static_assert(offsetof(DataflowHandlerArgs, handoff_stage_count) == 44,
              "DataflowHandlerArgs::handoff_stage_count ABI offset mismatch");
static_assert(offsetof(DataflowHandlerArgs, handoff_arena_slot) == 48,
              "DataflowHandlerArgs::handoff_arena_slot ABI offset mismatch");
static_assert(offsetof(DataflowHandlerArgs, handoff_flags) == 52,
              "DataflowHandlerArgs::handoff_flags ABI offset mismatch");
static_assert(offsetof(DataflowHandlerArgs, reserved0) == 56,
              "DataflowHandlerArgs::reserved0 ABI offset mismatch");
static_assert(offsetof(DataflowHandlerArgs, reserved1) == 60,
              "DataflowHandlerArgs::reserved1 ABI offset mismatch");

struct alignas(16) DataflowTensorArg {
  uint64_t data_ptr;
  uint32_t ndim;
  uint32_t dtype_code;
  uint32_t dtype_bits;
  uint32_t flags;
  uint64_t reserved;
};

static_assert(sizeof(DataflowTensorArg) == 32,
              "DataflowTensorArg ABI size mismatch");
static_assert(alignof(DataflowTensorArg) == 16,
              "DataflowTensorArg ABI alignment mismatch");
static_assert(offsetof(DataflowTensorArg, data_ptr) == 0,
              "DataflowTensorArg::data_ptr ABI offset mismatch");
static_assert(offsetof(DataflowTensorArg, ndim) == 8,
              "DataflowTensorArg::ndim ABI offset mismatch");
static_assert(offsetof(DataflowTensorArg, dtype_code) == 12,
              "DataflowTensorArg::dtype_code ABI offset mismatch");
static_assert(offsetof(DataflowTensorArg, dtype_bits) == 16,
              "DataflowTensorArg::dtype_bits ABI offset mismatch");
static_assert(offsetof(DataflowTensorArg, flags) == 20,
              "DataflowTensorArg::flags ABI offset mismatch");
static_assert(offsetof(DataflowTensorArg, reserved) == 24,
              "DataflowTensorArg::reserved ABI offset mismatch");

struct alignas(16) DataflowSlot {
  uint32_t shared_offset;
  uint32_t global_offset;
  uint32_t bytes;
  uint32_t flag_index;
  uint32_t barrier_index;
  uint32_t owner_cta;
  uint32_t flags;
  uint32_t reserved;
};

static_assert(sizeof(DataflowSlot) == 32, "DataflowSlot ABI size mismatch");
static_assert(alignof(DataflowSlot) == 16,
              "DataflowSlot ABI alignment mismatch");
static_assert(offsetof(DataflowSlot, shared_offset) == 0,
              "DataflowSlot::shared_offset ABI offset mismatch");
static_assert(offsetof(DataflowSlot, global_offset) == 4,
              "DataflowSlot::global_offset ABI offset mismatch");
static_assert(offsetof(DataflowSlot, bytes) == 8,
              "DataflowSlot::bytes ABI offset mismatch");
static_assert(offsetof(DataflowSlot, flag_index) == 12,
              "DataflowSlot::flag_index ABI offset mismatch");
static_assert(offsetof(DataflowSlot, barrier_index) == 16,
              "DataflowSlot::barrier_index ABI offset mismatch");
static_assert(offsetof(DataflowSlot, owner_cta) == 20,
              "DataflowSlot::owner_cta ABI offset mismatch");
static_assert(offsetof(DataflowSlot, flags) == 24,
              "DataflowSlot::flags ABI offset mismatch");
static_assert(offsetof(DataflowSlot, reserved) == 28,
              "DataflowSlot::reserved ABI offset mismatch");

struct alignas(16) DataflowCommPlan {
  uint32_t kind;
  uint32_t src_slot_id;
  uint32_t dst_slot_id;
  uint32_t peer_cta_rank;
  uint32_t barrier_phase;
  uint32_t flag_index;
  uint32_t flag_epoch;
  uint32_t barrier_index;
  uint32_t byte_offset;
  uint32_t byte_count;
  uint32_t segment_id;
  uint32_t segment_count;
};

static_assert(sizeof(DataflowCommPlan) == 48,
              "DataflowCommPlan ABI size mismatch");
static_assert(alignof(DataflowCommPlan) == 16,
              "DataflowCommPlan ABI alignment mismatch");
static_assert(offsetof(DataflowCommPlan, kind) == 0,
              "DataflowCommPlan::kind ABI offset mismatch");
static_assert(offsetof(DataflowCommPlan, src_slot_id) == 4,
              "DataflowCommPlan::src_slot_id ABI offset mismatch");
static_assert(offsetof(DataflowCommPlan, dst_slot_id) == 8,
              "DataflowCommPlan::dst_slot_id ABI offset mismatch");
static_assert(offsetof(DataflowCommPlan, peer_cta_rank) == 12,
              "DataflowCommPlan::peer_cta_rank ABI offset mismatch");
static_assert(offsetof(DataflowCommPlan, barrier_phase) == 16,
              "DataflowCommPlan::barrier_phase ABI offset mismatch");
static_assert(offsetof(DataflowCommPlan, flag_index) == 20,
              "DataflowCommPlan::flag_index ABI offset mismatch");
static_assert(offsetof(DataflowCommPlan, flag_epoch) == 24,
              "DataflowCommPlan::flag_epoch ABI offset mismatch");
static_assert(offsetof(DataflowCommPlan, barrier_index) == 28,
              "DataflowCommPlan::barrier_index ABI offset mismatch");
static_assert(offsetof(DataflowCommPlan, byte_offset) == 32,
              "DataflowCommPlan::byte_offset ABI offset mismatch");
static_assert(offsetof(DataflowCommPlan, byte_count) == 36,
              "DataflowCommPlan::byte_count ABI offset mismatch");
static_assert(offsetof(DataflowCommPlan, segment_id) == 40,
              "DataflowCommPlan::segment_id ABI offset mismatch");
static_assert(offsetof(DataflowCommPlan, segment_count) == 44,
              "DataflowCommPlan::segment_count ABI offset mismatch");

static constexpr uint32_t kDataflowInstructionClusterCommCountMask = 0xffffu;
static constexpr uint32_t kDataflowInstructionClusterSendCountShift = 16u;

} // namespace tl
